/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Outlet {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'location' : string,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface StoredAuditSubmission {
  'id' : string,
  'auditId' : string,
  'outletName' : string,
  'auditorId' : string,
  'auditorName' : string,
  'submittedAt' : string,
  'score' : bigint,
  'payload' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOutlet' : ActorMethod<[string, string], bigint>,
  'createUser' : ActorMethod<[Principal, string, string, string], undefined>,
  'deleteOutlet' : ActorMethod<[bigint], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'getAllOutlets' : ActorMethod<[], Array<Outlet>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOutlet' : ActorMethod<[bigint], Outlet>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'resetUserPassword' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOutlet' : ActorMethod<[bigint, string, string], undefined>,
  'updateUser' : ActorMethod<[Principal, string, string, string], undefined>,
  'submitAuditSubmission' : ActorMethod<[StoredAuditSubmission], undefined>,
  'getAllAuditSubmissions' : ActorMethod<[], Array<StoredAuditSubmission>>,
  'getAuditSubmissionById' : ActorMethod<[string], [] | [StoredAuditSubmission]>,
  'deleteAuditSubmission' : ActorMethod<[string], undefined>,
  'deleteAuditSubmissionsByOutlet' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
